import { notFound } from 'next/navigation';
import Link from 'next/link';

const GUIDE_CONTENT = {
  'energy-recharge-and-rotations': {
    title: 'Energy Recharge & Combat Rotations 101',
    category: 'Combat & Mechanics',
    readTime: '6 min read',
    lastUpdated: 'Version 5.x',
    content: `
### The Fundamentals of Energy

In Genshin Impact, casting an Elemental Burst requires a specific amount of Energy (ranging from 40 to 90 Energy points). If your burst is not ready when your rotation loops back to that character, your team's DPS drops drastically.

#### Particles vs. Orbs
- **Elemental Particles:** Generated by Elemental Skills (e.g. Bennett's Passion Overload generates 2-3 Pyro particles).
- **Clear (White) Particles:** Generated by dropping enemy HP thresholds (66%, 33%, 0%) or weapons like the **Favonius Series**. These yield universal energy to all party members.

#### On-Field vs. Off-Field Absorption
Characters absorb **considerably more energy** when active on-field:
- On-field same element: 3.0 Energy per particle
- Off-field same element: 1.8 Energy per particle
- On-field different element: 1.0 Energy per particle
- Off-field different element: 0.6 Energy per particle

#### Funneling Technique
Cast your battery's skill (e.g., Bennett E or Diona E) and **immediately switch** to your high-cost burst character (e.g., Xiangling or Ayaka) before the particles fly into your character. This ensures the target catches the particles on-field for 300% efficiency.
    `,
  },
  'elemental-reactions-and-gauge-theory': {
    title: 'Elemental Reactions & Gauge Theory Demystified',
    category: 'Theorycrafting',
    readTime: '10 min read',
    lastUpdated: 'Version 5.x',
    content: `
### What is Gauge Unit Theory?

Every elemental application possesses a "strength" measured in Units (U):
- **1U (Weak):** Lasts 9.5 seconds as aura. Most normal attacks and skills.
- **2U (Strong):** Lasts 12.0 seconds as aura. Certain bursts (e.g. Bennett Burst, Beidou Burst).

#### Forward vs. Reverse Reactions
- **Reverse Vaporize (Pyro onto Hydro):** Consumes only 0.5x gauge of Hydro. This allows Pyro DPS (Hu Tao, Xiangling) to continuously vaporize every hit on an existing Hydro aura.
- **Forward Vaporize (Hydro onto Pyro):** Consumes 2.0x gauge of Pyro. The aura disappears immediately after 1 hit.

#### Internal Cooldown (ICD)
The standard ICD rule is **3 hits or 2.5 seconds**, whichever comes first. This means not every strike of a multi-hit attack applies element. Characters without standard ICD (e.g., Xiangling's Pyronado has 0 ICD) are considered top-tier because every single hit triggers a reaction.
    `,
  },
  'resin-efficiency-and-progression': {
    title: 'Resin Efficiency: The AR 1 to AR 60 Roadmap',
    category: 'Account Progression',
    readTime: '8 min read',
    lastUpdated: 'Version 5.x',
    content: `
### The Golden Rule of Resin Allocation

Never spend fragile resin before **Adventure Rank 45**. At AR 45, the highest-difficulty artifact domains unlock with a guaranteed 5-star artifact per 20 resin spent.

#### Guaranteed Returns vs RNG Gambling
1. **Tier 1 (100% Guaranteed Value):** Weapon level 1 to 90. Base attack is immutable and scales all percentage multipliers.
2. **Tier 2 (100% Guaranteed Value):** Character core talent levels to 8. Each level provides ~6-7% DPS.
3. **Tier 3 (100% Guaranteed Value):** Character ascension to 80/90.
4. **Tier 4 (High RNG):** Artifact 5-star set farming. Secure the correct Main Stat (+20) first before chasing double-crit substats.
    `,
  },
  'artifact-optimization-and-crit-ratio': {
    title: 'Artifact Roll Value & The 1:2 CRIT Golden Rule',
    category: 'Optimization',
    readTime: '7 min read',
    lastUpdated: 'Version 5.x',
    content: `
### The 1:2 CRIT Ratio Explained

Mathematical expected damage is calculated as:
\`\`\`
Multiplier = 1 + (CRIT Rate × CRIT DMG)
\`\`\`
Because 1% CRIT Rate is allocated the exact same artifact budget as 2% CRIT DMG, the mathematical maximum area of the rectangle occurs when:
\`\`\`
CRIT DMG = 2 × CRIT Rate
\`\`\`
For example:
- **70% CRIT Rate / 140% CRIT DMG:** Expected bonus = 1 + (0.70 × 1.40) = 1.98x
- **50% CRIT Rate / 180% CRIT DMG:** Expected bonus = 1 + (0.50 × 1.80) = 1.90x

Even though total CV (Crit Value) is identical, the 1:2 ratio yields **higher average DPS**.
    `,
  },
};

export async function generateMetadata({ params }) {
  const { slug } = await params;
  const guide = GUIDE_CONTENT[slug];
  if (!guide) return { title: 'Guide Not Found' };

  return {
    title: `${guide.title} | Genshin Impact Guide`,
    description: `Read ${guide.title} covering ${guide.category}. Clear, actionable guidance for Genshin Impact players.`,
  };
}

export default async function GuideDetailPage({ params }) {
  const { slug } = await params;
  const guide = GUIDE_CONTENT[slug];

  if (!guide) {
    notFound();
  }

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: 'var(--space-8) var(--space-4) var(--space-16)' }}>
      <div style={{ marginBottom: 'var(--space-6)' }}>
        <Link href="/guides" style={{ color: 'var(--color-primary)', fontSize: 'var(--text-xs)', fontWeight: 'bold', textDecoration: 'none' }}>
          &larr; Back to Guides Library
        </Link>
      </div>

      <article
        style={{
          background: 'var(--bg-secondary)',
          border: '1px solid var(--border-primary)',
          borderRadius: 'var(--radius-2xl)',
          padding: 'var(--space-8)',
          boxShadow: 'var(--shadow-md)',
        }}
      >
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginBottom: 'var(--space-3)' }}>
          <span style={{ fontSize: '11px', color: 'var(--color-primary)', fontWeight: 'bold', textTransform: 'uppercase' }}>
            {guide.category}
          </span>
          <span style={{ color: 'var(--text-tertiary)' }}>&bull;</span>
          <span style={{ fontSize: '11px', color: 'var(--text-tertiary)' }}>
            {guide.readTime}
          </span>
          <span style={{ color: 'var(--text-tertiary)' }}>&bull;</span>
          <span style={{ fontSize: '11px', color: 'var(--text-tertiary)' }}>
            {guide.lastUpdated}
          </span>
        </div>

        <h1 style={{ fontSize: 'var(--text-2xl)', fontWeight: 'var(--weight-black)', marginBottom: 'var(--space-6)', color: 'var(--text-primary)' }}>
          {guide.title}
        </h1>

        <div
          style={{
            color: 'var(--text-secondary)',
            fontSize: 'var(--text-sm)',
            lineHeight: 1.8,
            whiteSpace: 'pre-line',
          }}
        >
          {guide.content}
        </div>
      </article>
    </div>
  );
}
